### ISSUE TITLE
main-maintainer change from t9md to jrajav

### ISSUE THREAD

**Issue by t9md** [jrajav/atom-lazy-motion#1]
t9md/atom-lazy-motion#16

**Comment by jonvuri** [comment]
Published and done, closing (Main discussion in original repo issue linked above).

**Comment by t9md** [comment]
Thanks!

**Comment by t9md** [comment]
I want make my stance clear, I'm glad you give me credit original package on readme(as you add at footer of readme).

Other than that, you can remove/change any code, any comment, any documentation as you like.
Don't pay too much respect for the history of this package, please change it as you like!

**Comment by jonvuri** [comment]
@t9md Noted, thanks! It works pretty solidly already so the most I'd do is a few extra quality-of-life improvements like that one open issue for now.
